/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "ask1.h"

bool_t
xdr_int_vector (XDR *xdrs, int_vector *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->data.data_val, (u_int *) &objp->data.data_len, ~0,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_minmax_result (XDR *xdrs, minmax_result *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->min))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->max))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_scalar_vector_input (XDR *xdrs, scalar_vector_input *objp)
{
	register int32_t *buf;

	 if (!xdr_float (xdrs, &objp->a))
		 return FALSE;
	 if (!xdr_int_vector (xdrs, &objp->vec))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_float_vector (XDR *xdrs, float_vector *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->data.data_val, (u_int *) &objp->data.data_len, ~0,
		sizeof (float), (xdrproc_t) xdr_float))
		 return FALSE;
	return TRUE;
}
