/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "ask1.h"
#include "common.h"

//1: Mean value
float *
mean_1_svc(int_vector *argp, struct svc_req *rqstp)
{
	static float  result;
	unsigned int i, n;
	int sum= 0;

	result= 0.0;
	n= argp->data.data_len;

	if(n== 0) return &result;
	
	for(i= 0; i< n; i++){
		sum+= argp->data.data_val[i];
	}
	
	result= (float)sum/n;
	return &result;
}

//2: Min - Max
minmax_result *
minmax_1_svc(int_vector *argp, struct svc_req *rqstp)
{
	static minmax_result  result;
	unsigned int i, n;

	result.min= 0;
	result.max= 0;

	n= argp->data.data_len;
	if(n== 0) return &result;

	result.min= argp->data.data_val[0];
	result.max= argp->data.data_val[0];

	for(i= 1; i< n; i++){
		if(argp->data.data_val[i]< result.min)
			result.min= argp->data.data_val[i];
		
		if(argp->data.data_val[i]> result.max)
			result.max= argp->data.data_val[i];
	}

	return &result;
}

//3: a*Y
float_vector *
multiply_1_svc(scalar_vector_input *argp, struct svc_req *rqstp)
{
	static float_vector  result;
	static float values[MAX_ELEMENTS];
	unsigned int i, n;

	result.data.data_val= values;
	result.data.data_len= 0;

	n= argp->vec.data.data_len;

	if(n> MAX_ELEMENTS)
		return &result;
	
	for(i= 0; i< n; i++){
		values[i]= argp->a*argp->vec.data.data_val[i];
	}

	result.data.data_len= n;
	return &result;
}
