/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "ask1.h"


void
calc_prog_1(char *host)
{
	CLIENT *clnt;
	float  *result_1;
	int_vector  mean_1_arg;
	minmax_result  *result_2;
	int_vector  minmax_1_arg;
	float_vector  *result_3;
	scalar_vector_input  multiply_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, CALC_PROG, CALC_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = mean_1(&mean_1_arg, clnt);
	if (result_1 == (float *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = minmax_1(&minmax_1_arg, clnt);
	if (result_2 == (minmax_result *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_3 = multiply_1(&multiply_1_arg, clnt);
	if (result_3 == (float_vector *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	calc_prog_1 (host);
exit (0);
}
