/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _ASK1_H_RPCGEN
#define _ASK1_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct int_vector {
	struct {
		u_int data_len;
		int *data_val;
	} data;
};
typedef struct int_vector int_vector;

struct minmax_result {
	int min;
	int max;
};
typedef struct minmax_result minmax_result;

struct scalar_vector_input {
	float a;
	int_vector vec;
};
typedef struct scalar_vector_input scalar_vector_input;

struct float_vector {
	struct {
		u_int data_len;
		float *data_val;
	} data;
};
typedef struct float_vector float_vector;

#define CALC_PROG 0x164E882
#define CALC_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define MEAN 1
extern  float * mean_1(int_vector *, CLIENT *);
extern  float * mean_1_svc(int_vector *, struct svc_req *);
#define MINMAX 2
extern  minmax_result * minmax_1(int_vector *, CLIENT *);
extern  minmax_result * minmax_1_svc(int_vector *, struct svc_req *);
#define MULTIPLY 3
extern  float_vector * multiply_1(scalar_vector_input *, CLIENT *);
extern  float_vector * multiply_1_svc(scalar_vector_input *, struct svc_req *);
extern int calc_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define MEAN 1
extern  float * mean_1();
extern  float * mean_1_svc();
#define MINMAX 2
extern  minmax_result * minmax_1();
extern  minmax_result * minmax_1_svc();
#define MULTIPLY 3
extern  float_vector * multiply_1();
extern  float_vector * multiply_1_svc();
extern int calc_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_int_vector (XDR *, int_vector*);
extern  bool_t xdr_minmax_result (XDR *, minmax_result*);
extern  bool_t xdr_scalar_vector_input (XDR *, scalar_vector_input*);
extern  bool_t xdr_float_vector (XDR *, float_vector*);

#else /* K&R C */
extern bool_t xdr_int_vector ();
extern bool_t xdr_minmax_result ();
extern bool_t xdr_scalar_vector_input ();
extern bool_t xdr_float_vector ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_ASK1_H_RPCGEN */
